FROM postgres:15

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=SqlFluff_01
ENV DB_LANG=ja_JP
ENV POSTGRES_DB=dev

RUN localedef -i $DB_LANG -c -f UTF-8 -A /usr/share/locale/locale.alias $DB_LANG.UTF-8
ENV LANG $DB_LANG.utf8
